## 第一題
### 有A,B,C三個班級，每班皆有10個學生，期中考結束後，老師希望計算各班級每位學生的加權平均成績。
### 請隨機產生3個班級的成績單,每班10人,共五科,權重為weights=[0.25,0.25,0.25,0.15,0.10]。
### 請算出班級加權平均成績，並以一個array輸出。

In [14]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [31]:
gradeA =np.array(np.random.randint(0,100,[10,5]))
gradeB =np.array(np.random.randint(0,100,[10,5]))
gradeC =np.array(np.random.randint(0,100,[10,5]))

In [32]:
print(gradeA)
print(gradeB)
print(gradeC)

[[27 92 53 27  3]
 [ 1 51 67 72 18]
 [50 59 62 73 74]
 [34 43 58 64 82]
 [ 3 29  2 53 66]
 [40 42 82 65 22]
 [97 70 36 30 55]
 [13 44 41 79  8]
 [50 72 70 87 44]
 [45 73 93 67  9]]
[[17 28 64 36 51]
 [ 7 24 42 11 51]
 [60 13 95 20 34]
 [35 61 67 56 93]
 [68 19 11  6 35]
 [40 50 81 68 54]
 [89 17 38 72 50]
 [83 45 70 95 48]
 [82 86 71 33  7]
 [ 4  4 85 54 49]]
[[58 36 86 52 17]
 [39 91 49  4 48]
 [44 45 92 58 61]
 [57 76 74 78 36]
 [91 92 65 14 25]
 [43 84 39 19 55]
 [65 28 25 23 23]
 [78 34 86 38 42]
 [97 58 24 49 96]
 [80  8 15 70 16]]


In [33]:
weight=np.array([0.25,0.25,0.25,0.15,0.10])
A=np.dot(gradeA,weight)
B=np.dot(gradeB,weight)
C=np.dot(gradeC,weight)

In [35]:
print(A)
print(B)
print(C)

[47.35 42.35 61.1  51.55 23.05 52.95 60.75 37.15 65.45 63.7 ]
[37.75 25.   48.4  58.45 28.9  58.35 51.8  68.55 65.4  36.25]
[54.5  50.15 60.05 67.05 66.6  49.85 35.25 59.4  61.7  37.85]
